name: python test
on:
  workflow_dispatch: # 保留手动触发，也可以根据实际情况选择其他触发器

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 根据项目需求选择合适的Python版本

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Test Script
      run: |
        python test/test.py
