name: Run Test Script on Linux
on:
  push:
    branches: [ 'main' ] # 触发构建的分支

jobs:
  run_script:
    runs-on: ubuntu-latest # 使用最新版本的Ubuntu作为运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 根据项目需求选择合适的Python版本

    - name: Run Test Script
      run: |
<<<<<<< HEAD
        python test.py
=======
         pip install -r requirements.txt -r requirements-dev.txt

      - name: Build Executable with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
         nuitka-version: main
         script-name: test.py
         # many more Nuitka options available, see action doc, but it's best
         # to use nuitka-project: options in your code, so e.g. you can make
         # a difference for macOS and create an app bundle there.
         onefile: true

      - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
         name: ${{ runner.os }} Build
         path: | # match what's created for the 3 OSes
            build/*.exe
            build/*.bin
            build/*.app/**/*
>>>>>>> f5f3db11bce133891d445e0f79abf2151c847ad8
